// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripBookingBE.Data;

#nullable disable

namespace TripBookingBE.Migrations
{
    [DbContext(typeof(TripBookingContext))]
    [Migration("20250722143754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripBookingBE.Models.CustomerBookTrip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.Property<int?>("PlaceNumber")
                        .HasColumnType("int")
                        .HasColumnName("placeNumber");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("tripId");

                    b.HasKey("Id")
                        .HasName("PK_CustomerBookTrip_1");

                    b.HasIndex("TripId");

                    b.HasIndex(new[] { "CustomerId", "TripId" }, "IX_CustomerBookTrip")
                        .IsUnique();

                    b.ToTable("CustomerBookTrip");
                });

            modelBuilder.Entity("TripBookingBE.Models.CustomerReviewTrip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("tripId");

                    b.HasKey("Id")
                        .HasName("PK_UserReviewTrip");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TripId");

                    b.ToTable("CustomerReviewTrip");
                });

            modelBuilder.Entity("TripBookingBE.Models.Route", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.Property<string>("RouteDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("routeDescription");

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("TripBookingBE.Models.SellerTrip", b =>
                {
                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("sellerId");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("tripId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.HasKey("SellerId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("SellerTrip");
                });

            modelBuilder.Entity("TripBookingBE.Models.Ticket", b =>
                {
                    b.Property<long>("CustomerBookTripId")
                        .HasColumnType("bigint")
                        .HasColumnName("customerBookTripId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<string>("SellerCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sellerCode");

                    b.HasKey("CustomerBookTripId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("TripBookingBE.Models.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified");

                    b.Property<DateTime?>("DepartureTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("departureTime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("DriverId")
                        .HasColumnType("bigint")
                        .HasColumnName("driverId");

                    b.Property<int?>("PlaceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("placeCount");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registrationNumber");

                    b.Property<long?>("RouteId")
                        .HasColumnType("bigint")
                        .HasColumnName("routeId");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("TripBookingBE.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("avatar")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateModified")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("firstName");

                    b.Property<DateTime?>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("lastLogin")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("lastName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("SellerCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sellerCode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("CUSTOMER")
                        .HasColumnName("type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("userName");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F36DAC7FF");

                    b.HasIndex(new[] { "UserName" }, "UQ__User__66DCF95C55A682B1")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("TripBookingBE.Models.CustomerBookTrip", b =>
                {
                    b.HasOne("TripBookingBE.Models.User", "Customer")
                        .WithMany("CustomerBookTrips")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerBookTrip_User");

                    b.HasOne("TripBookingBE.Models.Trip", "Trip")
                        .WithMany("CustomerBookTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerBookTrip_Trip");

                    b.Navigation("Customer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripBookingBE.Models.CustomerReviewTrip", b =>
                {
                    b.HasOne("TripBookingBE.Models.User", "Customer")
                        .WithMany("CustomerReviewTrips")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserReviewTrip_User");

                    b.HasOne("TripBookingBE.Models.Trip", "Trip")
                        .WithMany("CustomerReviewTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserReviewTrip_Trip");

                    b.Navigation("Customer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripBookingBE.Models.SellerTrip", b =>
                {
                    b.HasOne("TripBookingBE.Models.Trip", "Trip")
                        .WithMany("SellerTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SellerTrip_Trip");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripBookingBE.Models.Ticket", b =>
                {
                    b.HasOne("TripBookingBE.Models.CustomerBookTrip", "CustomerBookTrip")
                        .WithOne("Ticket")
                        .HasForeignKey("TripBookingBE.Models.Ticket", "CustomerBookTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_CustomerBookTrip");

                    b.Navigation("CustomerBookTrip");
                });

            modelBuilder.Entity("TripBookingBE.Models.Trip", b =>
                {
                    b.HasOne("TripBookingBE.Models.User", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("FK_Trip_User");

                    b.HasOne("TripBookingBE.Models.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("FK_Trip_Route");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TripBookingBE.Models.CustomerBookTrip", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TripBookingBE.Models.Route", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TripBookingBE.Models.Trip", b =>
                {
                    b.Navigation("CustomerBookTrips");

                    b.Navigation("CustomerReviewTrips");

                    b.Navigation("SellerTrips");
                });

            modelBuilder.Entity("TripBookingBE.Models.User", b =>
                {
                    b.Navigation("CustomerBookTrips");

                    b.Navigation("CustomerReviewTrips");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
